//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPlane
    {
        public int ID { get; set; }
        public Nullable<int> PlaneNo { get; set; }
        public string PlaneName { get; set; }
        public string Arrival { get; set; }
        public string destination { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
